# Generated by Django 5.2.15 on 2026-07-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره قسمت')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان قسمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت\u200cها',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.movie',),
        ),
        migrations.CreateModel(
            name='EpisodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('subtitle', 'زیرنویس فارسی'), ('dubbed', 'دوبله فارسی'), ('original', 'زبان اصلی')], max_length=10, verbose_name='نوع نسخه')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان نسخه')),
                ('language', models.CharField(default='فارسی', max_length=50, verbose_name='زبان')),
                ('has_subtitle', models.BooleanField(default=False, verbose_name='زیرنویس فارسی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='movies.episode', verbose_name='قسمت')),
            ],
            options={
                'verbose_name': 'نسخه قسمت',
                'verbose_name_plural': 'نسخه\u200cهای قسمت',
                'ordering': ['version_type'],
                'unique_together': {('episode', 'version_type')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره فصل')),
                ('title', models.CharField(blank=True, help_text='مثال: فصل اول', max_length=200, verbose_name='عنوان فصل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال انتشار')),
                ('episode_count', models.PositiveIntegerField(default=0, verbose_name='تعداد قسمت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.movie', verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season', verbose_name='فصل'),
        ),
        migrations.CreateModel(
            name='EpisodeDownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2160p', '4K')], max_length=10, verbose_name='کیفیت')),
                ('url', models.URLField(verbose_name='لینک دانلود')),
                ('file_size', models.CharField(blank=True, help_text='مثال: 350MB', max_length=20, verbose_name='حجم فایل')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='movies.episodeversion', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'لینک دانلود قسمت',
                'verbose_name_plural': 'لینک\u200cهای دانلود قسمت',
                'ordering': ['quality'],
                'unique_together': {('version', 'quality')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'number')},
        ),
    ]
